/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.teater;

import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author adima
 */
public class menuUtam_ok extends javax.swing.JFrame {
    
    koneksiDB x; //deklarasi kelas
    

    /**
     * Creates new form booking
    

    /**
     * Creates new form menuUtam
     */
    public menuUtam_ok() {
        initComponents();
        x=new koneksiDB();
        x.koneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Menu_Studio1 = new javax.swing.JButton();
        Menu_Studio2 = new javax.swing.JButton();
        Exit_MenuUtam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Selamat datang");

        Menu_Studio1.setText("Studio 1");
        Menu_Studio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Studio1ActionPerformed(evt);
            }
        });

        Menu_Studio2.setText("Studio 2");
        Menu_Studio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Studio2ActionPerformed(evt);
            }
        });

        Exit_MenuUtam.setText("Exit");
        Exit_MenuUtam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit_MenuUtamMouseClicked(evt);
            }
        });
        Exit_MenuUtam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_MenuUtamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(Menu_Studio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Menu_Studio2)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(Exit_MenuUtam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Menu_Studio2)
                    .addComponent(Menu_Studio1))
                .addGap(58, 58, 58)
                .addComponent(Exit_MenuUtam)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_Studio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Studio1ActionPerformed
        // TODO add your handling code here:
        
        new Studio1_pagi().setVisible(true); //membuat frame studio muncul
dispose(); //membuat frame menuUtama tertutup
    }//GEN-LAST:event_Menu_Studio1ActionPerformed

    private void Menu_Studio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Studio2ActionPerformed
        // TODO add your handling code here:
        new std2_pagi().setVisible(true); //membuat frame studio muncul
dispose(); //membuat frame menuUtama tertutup
    }//GEN-LAST:event_Menu_Studio2ActionPerformed

    private void Exit_MenuUtamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_MenuUtamActionPerformed
        // TODO add your handling code here:
        if ( JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar ?","Konfirmasi", //
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION)
System.exit(0); //membuat keluar dari aplikasi
    }//GEN-LAST:event_Exit_MenuUtamActionPerformed

    private void Exit_MenuUtamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_MenuUtamMouseClicked
        // TODO add your handling code here:
        if ( JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar ?","Konfirmasi", //
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION)
System.exit(0); //membuat keluar dari aplikasi
    }//GEN-LAST:event_Exit_MenuUtamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtam_ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtam_ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtam_ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtam_ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUtam_ok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit_MenuUtam;
    private javax.swing.JButton Menu_Studio1;
    private javax.swing.JButton Menu_Studio2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
