/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.teater;

import java.sql.ResultSet;
import javax.swing.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author adima
 */
public class std2_siang extends javax.swing.JFrame {
    
    koneksiDB x;

    /**
     * Creates new form std2_siang
     */
    public std2_siang() {
        try {
            initComponents();
            x = new koneksiDB();
            x.koneksi(); //panggil koneksi
            String q ="SELECT * FROM studio2_siang";
            x.pst=x.conn.prepareStatement(q);
            x.rs=x.pst.executeQuery();
            
            while(x.rs.next()){
                if(studio2_siang_Kursi_A1.getText().equals(x.rs.getString(1))){
                    studio2_siang_Kursi_A1.setEnabled(false);
                    System.out.println("Ini jalan");
                }
                if(studio2_siang_Kursi_B2.getText().equals(x.rs.getString(1)))
                {
                    studio2_siang_Kursi_B2.setEnabled(false);
                }
            }       } catch (SQLException ex) {
            Logger.getLogger(std2_siang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studio2_siang_Screen = new javax.swing.JLabel();
        studio2_siang_Book_Button = new javax.swing.JButton();
        studio2_siang_Back_Button = new javax.swing.JButton();
        studio2_siang_Kursi_A1 = new javax.swing.JCheckBox();
        studio2_siang_Kursi_B2 = new javax.swing.JCheckBox();
        label_siang_TotalHarga2 = new javax.swing.JLabel();
        studio2_siang_Screen_Film = new javax.swing.JLabel();
        studio2_siang_NamaStudio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studio2_siang_Screen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        studio2_siang_Screen.setText("SCREEN");

        studio2_siang_Book_Button.setText("Book");
        studio2_siang_Book_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studio2_siang_Book_ButtonActionPerformed(evt);
            }
        });

        studio2_siang_Back_Button.setText("Back");
        studio2_siang_Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studio2_siang_Back_ButtonActionPerformed(evt);
            }
        });

        studio2_siang_Kursi_A1.setText("A1");
        studio2_siang_Kursi_A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studio2_siang_Kursi_A1ActionPerformed(evt);
            }
        });

        studio2_siang_Kursi_B2.setText("B2");
        studio2_siang_Kursi_B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studio2_siang_Kursi_B2ActionPerformed(evt);
            }
        });

        label_siang_TotalHarga2.setText("Total harga : ");

        studio2_siang_Screen_Film.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        studio2_siang_Screen_Film.setText("Film : Koala Kumal");

        studio2_siang_NamaStudio.setText("Studio 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(studio2_siang_Screen)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studio2_siang_Kursi_B2)
                    .addComponent(studio2_siang_Kursi_A1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_siang_TotalHarga2)
                            .addComponent(studio2_siang_Back_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studio2_siang_Book_Button)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studio2_siang_Screen_Film)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studio2_siang_NamaStudio)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(studio2_siang_Screen)
                .addGap(43, 43, 43)
                .addComponent(studio2_siang_Kursi_A1)
                .addGap(18, 18, 18)
                .addComponent(studio2_siang_Kursi_B2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studio2_siang_Screen_Film)
                    .addComponent(studio2_siang_NamaStudio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_siang_TotalHarga2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studio2_siang_Book_Button)
                    .addComponent(studio2_siang_Back_Button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studio2_siang_Book_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studio2_siang_Book_ButtonActionPerformed
        // TODO add your handling code here:

        String film2_siang, studio2_siang, kodeKursi2_siang="", sql1, sql2;
        film2_siang = (String) studio2_siang_Screen_Film.getText();
        studio2_siang = (String) studio2_siang_NamaStudio.getText();
        if(studio2_siang_Kursi_A1.isSelected())
        {
            kodeKursi2_siang=studio2_siang_Kursi_A1.getText();
            sql1 = "INSERT INTO studio2_siang VALUES ('"+kodeKursi2_siang+"', '"+film2_siang+"', '"+studio2_siang+"')";

            try
            {
                x.st = x.conn.createStatement();
                x.st.execute(sql1);

            }
            catch (SQLException e){
                System.out.print(e);
                JOptionPane.showMessageDialog(null, "sudah dibooking sebelumnya");
                return;
            }

        }

        if(studio2_siang_Kursi_B2.isSelected())
        {
            kodeKursi2_siang=studio2_siang_Kursi_B2.getText();
            sql1 = "INSERT INTO studio2_siang VALUES ('"+kodeKursi2_siang+"', '"+film2_siang+"', '"+studio2_siang+"')";

            try
            {
                x.st = x.conn.createStatement();
                x.st.execute(sql1);

            }
            catch (SQLException e){
                System.out.print(e);
                JOptionPane.showMessageDialog(null, "sudah dibooking sebelumnya");
                return;
            }

        }

        JOptionPane.showMessageDialog(null, "Berhasil di pesan, Terima kasih :)");
        sql2 = "delete from inputan where kodeKursi2_siang='"+kodeKursi2_siang+"'";
        try
        {
            x.st = x.conn.createStatement();
            x.st.execute(sql2);
        }
        catch (SQLException e){
        }
    }//GEN-LAST:event_studio2_siang_Book_ButtonActionPerformed

    private void studio2_siang_Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studio2_siang_Back_ButtonActionPerformed
        // TODO add your handling code here:
        new indonesia_movie().setVisible(true);
        dispose();
    }//GEN-LAST:event_studio2_siang_Back_ButtonActionPerformed
int harga=0;
    private void studio2_siang_Kursi_A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studio2_siang_Kursi_A1ActionPerformed

        // TODO add your handling code here:

        if(studio2_siang_Kursi_A1.isSelected())
        {
            harga = harga+20000;
        }
        else {
            harga=harga-20000;
        }
        label_siang_TotalHarga2.setText("total harga : Rp."+String.valueOf(harga));
    }//GEN-LAST:event_studio2_siang_Kursi_A1ActionPerformed

    private void studio2_siang_Kursi_B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studio2_siang_Kursi_B2ActionPerformed
        // TODO add your handling code here:
        if(studio2_siang_Kursi_B2.isSelected())
        {
            harga = harga+20000;
        }
        else {
            harga= harga-20000;
        }
        label_siang_TotalHarga2.setText("total harga : Rp."+String.valueOf(harga));
    }//GEN-LAST:event_studio2_siang_Kursi_B2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(std2_siang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(std2_siang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(std2_siang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(std2_siang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new std2_siang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_siang_TotalHarga2;
    private javax.swing.JButton studio2_siang_Back_Button;
    private javax.swing.JButton studio2_siang_Book_Button;
    private javax.swing.JCheckBox studio2_siang_Kursi_A1;
    private javax.swing.JCheckBox studio2_siang_Kursi_B2;
    private javax.swing.JLabel studio2_siang_NamaStudio;
    private javax.swing.JLabel studio2_siang_Screen;
    private javax.swing.JLabel studio2_siang_Screen_Film;
    // End of variables declaration//GEN-END:variables
}
