/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.teater;


import java.sql.ResultSet;
import javax.swing.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author adima
 */
public class Studio1_malam extends javax.swing.JFrame {
    
    koneksiDB x;

    /**
     * Creates new form Studio1_malam
     */
    public Studio1_malam() {
        try {
            initComponents();
            x = new koneksiDB();
            x.koneksi(); //panggil koneksi
            String q ="SELECT * FROM studio1_malam";
            x.pst=x.conn.prepareStatement(q);
            x.rs=x.pst.executeQuery();
            
            while(x.rs.next()){
                if(Studio1_malam_Kursi_A2.getText().equals(x.rs.getString(1))){
                    Studio1_malam_Kursi_A2.setEnabled(false);
                    System.out.println("Ini jalan");
                }
                if(Studio1_malam_Kursi_B2.getText().equals(x.rs.getString(1)))
                {
                    Studio1_malam_Kursi_B2.setEnabled(false);
                }
            }       } catch (SQLException ex) {
            Logger.getLogger(Studio1_malam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Studio1_malam_Kursi_A2 = new javax.swing.JCheckBox();
        Studio1_malam_Kursi_B2 = new javax.swing.JCheckBox();
        label_malam_TotalHarga = new javax.swing.JLabel();
        Studio1_malam_Screen_Film = new javax.swing.JLabel();
        Studio1_malam_NamaStudio = new javax.swing.JLabel();
        Studio1_malam_Screen = new javax.swing.JLabel();
        Studio1_malam_Book_Button = new javax.swing.JButton();
        Studio1_malam_Back_Button = new javax.swing.JButton();
        Studio1_malam_Kursi_A3 = new javax.swing.JCheckBox();
        Studio1_malam_Kursi_B3 = new javax.swing.JCheckBox();
        Studio1_malam_Kursi_B4 = new javax.swing.JCheckBox();
        Studio1_malam_Kursi_A4 = new javax.swing.JCheckBox();
        Studio1_malam_Kursi_B1 = new javax.swing.JCheckBox();
        Studio1_malam_Kursi_A1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Studio1_malam_Kursi_A2.setText("A2");
        Studio1_malam_Kursi_A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Studio1_malam_Kursi_A2ActionPerformed(evt);
            }
        });

        Studio1_malam_Kursi_B2.setText("B2");
        Studio1_malam_Kursi_B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Studio1_malam_Kursi_B2ActionPerformed(evt);
            }
        });

        label_malam_TotalHarga.setText("Total harga : ");

        Studio1_malam_Screen_Film.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Studio1_malam_Screen_Film.setText("Film : Frozen");

        Studio1_malam_NamaStudio.setText("Studio 1");

        Studio1_malam_Screen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Studio1_malam_Screen.setText("SCREEN");

        Studio1_malam_Book_Button.setText("Book");
        Studio1_malam_Book_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Studio1_malam_Book_ButtonActionPerformed(evt);
            }
        });

        Studio1_malam_Back_Button.setText("Back");
        Studio1_malam_Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Studio1_malam_Back_ButtonActionPerformed(evt);
            }
        });

        Studio1_malam_Kursi_A3.setText("A3");
        Studio1_malam_Kursi_A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Studio1_malam_Kursi_A3ActionPerformed(evt);
            }
        });

        Studio1_malam_Kursi_B3.setText("B3");
        Studio1_malam_Kursi_B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Studio1_malam_Kursi_B3ActionPerformed(evt);
            }
        });

        Studio1_malam_Kursi_B4.setText("B4");
        Studio1_malam_Kursi_B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Studio1_malam_Kursi_B4ActionPerformed(evt);
            }
        });

        Studio1_malam_Kursi_A4.setText("A4");
        Studio1_malam_Kursi_A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Studio1_malam_Kursi_A4ActionPerformed(evt);
            }
        });

        Studio1_malam_Kursi_B1.setText("B1");
        Studio1_malam_Kursi_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Studio1_malam_Kursi_B1ActionPerformed(evt);
            }
        });

        Studio1_malam_Kursi_A1.setText("A1");
        Studio1_malam_Kursi_A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Studio1_malam_Kursi_A1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_malam_TotalHarga)
                            .addComponent(Studio1_malam_Back_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Studio1_malam_Book_Button)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Studio1_malam_Kursi_B1)
                                .addComponent(Studio1_malam_Kursi_A1))
                            .addComponent(Studio1_malam_Screen_Film))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Studio1_malam_Screen)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Studio1_malam_Kursi_B2)
                                    .addComponent(Studio1_malam_Kursi_A2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Studio1_malam_Kursi_B3)
                                    .addComponent(Studio1_malam_Kursi_A3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Studio1_malam_NamaStudio)
                            .addComponent(Studio1_malam_Kursi_B4)
                            .addComponent(Studio1_malam_Kursi_A4))
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Studio1_malam_Screen)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Studio1_malam_Kursi_A4)
                                    .addGap(18, 18, 18)
                                    .addComponent(Studio1_malam_Kursi_B4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Studio1_malam_Kursi_A3)
                                    .addGap(18, 18, 18)
                                    .addComponent(Studio1_malam_Kursi_B3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Studio1_malam_Kursi_A2)
                                .addGap(18, 18, 18)
                                .addComponent(Studio1_malam_Kursi_B2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Studio1_malam_Screen_Film)
                            .addComponent(Studio1_malam_NamaStudio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_malam_TotalHarga)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Studio1_malam_Book_Button)
                            .addComponent(Studio1_malam_Back_Button)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Studio1_malam_Kursi_A1)
                        .addGap(18, 18, 18)
                        .addComponent(Studio1_malam_Kursi_B1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int harga=0;
    private void Studio1_malam_Kursi_A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Studio1_malam_Kursi_A2ActionPerformed

        // TODO add your handling code here:

        if(Studio1_malam_Kursi_A2.isSelected())
        {
            harga = harga+20000;
        }
        else {
            harga=harga-20000;
        }
        label_malam_TotalHarga.setText("total harga : Rp."+String.valueOf(harga));
    }//GEN-LAST:event_Studio1_malam_Kursi_A2ActionPerformed

    private void Studio1_malam_Kursi_B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Studio1_malam_Kursi_B2ActionPerformed
        // TODO add your handling code here:
        if(Studio1_malam_Kursi_B2.isSelected())
        {
            harga = harga+20000;
        }
        else {
            harga= harga-20000;
        }
        label_malam_TotalHarga.setText("total harga : Rp."+String.valueOf(harga));
    }//GEN-LAST:event_Studio1_malam_Kursi_B2ActionPerformed

    private void Studio1_malam_Book_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Studio1_malam_Book_ButtonActionPerformed
        // TODO add your handling code here:

        String film_malam, studio_malam, kodeKursi_malam="", sql1, sql2;
        film_malam = (String) Studio1_malam_Screen_Film.getText();
        studio_malam = (String) Studio1_malam_NamaStudio.getText();
        if(Studio1_malam_Kursi_A2.isSelected())
        {
            kodeKursi_malam=Studio1_malam_Kursi_A2.getText();
            sql1 = "INSERT INTO studio1_malam VALUES ('"+kodeKursi_malam+"', '"+film_malam+"', '"+studio_malam+"')";

            try
            {
                x.st = x.conn.createStatement();
                x.st.execute(sql1);

            }
            catch (SQLException e){
                System.out.print(e);
                JOptionPane.showMessageDialog(null, "sudah dibooking sebelumnya");
                return;
            }

        }

        if(Studio1_malam_Kursi_B2.isSelected())
        {
            kodeKursi_malam=Studio1_malam_Kursi_B2.getText();
            sql1 = "INSERT INTO studio1_malam VALUES ('"+kodeKursi_malam+"', '"+film_malam+"', '"+studio_malam+"')";

            try
            {
                x.st = x.conn.createStatement();
                x.st.execute(sql1);

            }
            catch (SQLException e){
                System.out.print(e);
                JOptionPane.showMessageDialog(null, "sudah dibooking sebelumnya");
                return;
            }

        }

        JOptionPane.showMessageDialog(null, "Berhasil di pesan, Terima kasih :)");
        sql2 = "delete from inputan where kodeKursi1_malam='"+kodeKursi_malam+"'";
        try
        {
            x.st = x.conn.createStatement();
            x.st.execute(sql2);
        }
        catch (SQLException e){
        }
        new menuUtam().setVisible(true);
        dispose();
    }//GEN-LAST:event_Studio1_malam_Book_ButtonActionPerformed

    private void Studio1_malam_Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Studio1_malam_Back_ButtonActionPerformed
        // TODO add your handling code here:
        new holywood_movie().setVisible(true);
        dispose();
    }//GEN-LAST:event_Studio1_malam_Back_ButtonActionPerformed

    private void Studio1_malam_Kursi_A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Studio1_malam_Kursi_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Studio1_malam_Kursi_A3ActionPerformed

    private void Studio1_malam_Kursi_B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Studio1_malam_Kursi_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Studio1_malam_Kursi_B3ActionPerformed

    private void Studio1_malam_Kursi_B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Studio1_malam_Kursi_B4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Studio1_malam_Kursi_B4ActionPerformed

    private void Studio1_malam_Kursi_A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Studio1_malam_Kursi_A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Studio1_malam_Kursi_A4ActionPerformed

    private void Studio1_malam_Kursi_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Studio1_malam_Kursi_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Studio1_malam_Kursi_B1ActionPerformed

    private void Studio1_malam_Kursi_A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Studio1_malam_Kursi_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Studio1_malam_Kursi_A1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studio1_malam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studio1_malam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studio1_malam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studio1_malam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studio1_malam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Studio1_malam_Back_Button;
    private javax.swing.JButton Studio1_malam_Book_Button;
    private javax.swing.JCheckBox Studio1_malam_Kursi_A1;
    private javax.swing.JCheckBox Studio1_malam_Kursi_A2;
    private javax.swing.JCheckBox Studio1_malam_Kursi_A3;
    private javax.swing.JCheckBox Studio1_malam_Kursi_A4;
    private javax.swing.JCheckBox Studio1_malam_Kursi_B1;
    private javax.swing.JCheckBox Studio1_malam_Kursi_B2;
    private javax.swing.JCheckBox Studio1_malam_Kursi_B3;
    private javax.swing.JCheckBox Studio1_malam_Kursi_B4;
    private javax.swing.JLabel Studio1_malam_NamaStudio;
    private javax.swing.JLabel Studio1_malam_Screen;
    private javax.swing.JLabel Studio1_malam_Screen_Film;
    private javax.swing.JLabel label_malam_TotalHarga;
    // End of variables declaration//GEN-END:variables
}
